name: Build APK
on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Flet    
        run: pip install flet
      - name: Build APK  
        run: flet pack main.py --name "3D by NED"
      - name: Upload APK  
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: ./dist/*.apk
