name: Build APK
on: push

jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install flet
      - run: flet build apk --name "3D by NED" .
      - uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: build/apk/*.apk
